example/config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :books
  map.connect "/", :controller => "books"
end

example/app/models/author.rb
class Author < ActiveRecord::Base
end

example/app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :book
  belongs_to :author
  
  validates_presence_of :role
  
  # This creates an Authorship.build_from_authors method which we can pass a load of Authors and get
  # back a load of Authorships which are linked to those Authors.
  buildable_from :authors
  
  delegate :name, :to => :author, :prefix => true
  
  # Defining a sensible to_s is useful here, because if there are errors on an authorship the user
  # needs to be able to identify which one - the aggregated errors do this by calling to_s.
  def to_s
    author_name
  end
  
  # If there are errors and the form has to be re-rendered, we need a sensible definition of equality
  # so the currently unsaved authorships are used in the form rather than new ones - this means that
  # any changes the user has made are not lost.
  def ==(other)
    other.book_id == book_id && other.author_id == author_id
  end
end

example/app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  
  has_many :authorships, :dependent => :destroy
  has_many :authors, :through => :authorships
  
  has_and_belongs_to_many :tags
  
  validates_presence_of :name
  validates_presence_of :publisher_id, :message => "must exist"
  
  # Here we're finding all the authors and creating a load of Authorship instances which are linked
  # to those authors. This creates an array of all the authorships we might want to associate our
  # book with.
  def potential_authorships
    authorships.build_from_authors(*Author.find(:all))
  end
  
  def potential_publishers
    Publisher.find(:all)
  end
  
  def potential_tags
    Tag.find(:all)
  end
  
  def publisher_name
    publisher.name
  end
  
  def author_names_and_roles
    authorships.map { |authorship| "#{authorship.author_name} as #{authorship.role}" }
  end
end

example/app/models/publisher.rb
class Publisher < ActiveRecord::Base
  def to_s
    name
  end
end

example/app/models/tag.rb
class Tag < ActiveRecord::Base
  def to_s
    name
  end
end

example/app/controllers/application.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time

  # See ActionController::RequestForgeryProtection for details
  # Uncomment the :secret if you're not using the cookie session store
  protect_from_forgery # :secret => 'aed92883f82842cd9658bb296341e33d'
  
  # See ActionController::Base for details 
  # Uncomment this to filter the contents of submitted sensitive data parameters
  # from your application log (in this case, all fields with names like "password"). 
  # filter_parameter_logging :password
end

example/app/controllers/books_controller.rb
class BooksController < ApplicationController
  # Add some before filters to initialize the @book and @book_conductor variables before the 
  # relevant actions
  before_filter :find_or_initialize_book, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :initialize_book_conductor, :only => [:new, :create, :edit, :update]
  
  def index
    @books = Book.find(:all)
  end
  
  # Instead of calling @book.update_attributes we do it on the @book_conductor. This causes the
  # conductor to take care of all the messy details of what changes should happen base on the 
  # params, and it will ensure the changes are all written to the database in one transaction.
  def create
    if @book_conductor.update_attributes(params[:book])
      redirect_to books_path
    else
      render :action => "new"
    end
  end
  
  def update
    if @book_conductor.update_attributes(params[:book])
      redirect_to books_path
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @book.destroy
    redirect_to books_path
  end
  
  private
  
    def find_or_initialize_book
      if params[:id]
        @book = Book.find(params[:id])
      else
        @book = Book.new
      end
    end
    
    # The conductor is initialized with the record it is supposed to be managing updates to
    def initialize_book_conductor
      @book_conductor = BookConductor.new(@book)
    end
end

example/app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

example/app/views/books/_form.html.erb
<% form_for_conductor @book_conductor do |form| %>
  <%= error_messages_for_conductor :book_conductor %>
  
  <fieldset>
    <legend>Basic Details</legend>
    
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
    
    <p>
      <%= form.label :publisher %> (Options are <%= @book.potential_publishers.to_sentence %>.)<br>
      <%= form.text_field :publisher %>
    </p>
  </fieldset>
  
  <fieldset>
    <legend>Authors</legend>
  
    <table>
      <tr>
        <th>Name</th>
        <th>Role</th>
      </tr>
      
      <% form.fields_for_collection(:authorships, @book.potential_authorships) do |fields, authorship| -%>
        <tr>
          <td>
            <%= fields.inclusion_check_box :author_id %>
            <%= fields.label :author_id, authorship.author_name %>
          </td>
          <td>
            <%= fields.text_field :role %>
          </td>
        </tr>
      <% end -%>
    </table>
  </fieldset>
  
  <fieldset>
    <legend>Tags</legend>
    
    <% form.fields_for_collection_ids(:tag_ids, @book.potential_tags) do |fields, tag| -%>
      <%= fields.inclusion_check_box %>
      <%= fields.label -%>
    <% end -%>
  </fieldset>
  
  <p><%= form.submit %></p>
<% end %>

example/app/views/books/edit.html.erb
<h1>Edit Book</h1>

<%= render :partial => "form" %>

example/app/views/books/index.html.erb
<h1>Books</h1>

<p><%= link_to "New Book", new_book_path %></p>

<table class="books">
  <tr class="odd">
    <th>Name</th>
    <th>Publisher</th>
    <th>Authors</th>
    <th>Tags</th>
    <th></th>
    <th></th>
  </tr>
  
  <% @books.each do |book| -%>
    <tr class="<%= cycle('even', 'odd') %>">
      <th><%=h book.name %></th>
      <td><%=h book.publisher %></td>
      <td><%=h book.author_names_and_roles.to_sentence %></td>
      <td><%=h book.tags.to_sentence %></td>
      <td><%= link_to "Edit", edit_book_path(book) %></td>
      <td><%= link_to "Delete", book_path(book), :method => :delete %></td>
    <tr>
  <% end %>
</table>

example/app/views/books/new.html.erb
<h1>New Book</h1>

<%= render :partial => "form" %>

example/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <%= stylesheet_link_tag "application" %>
    <title>Conductor Example App</title>
  </head>
  <body>
    <%= yield %>
  </body>
</html>